### ISSUE TITLE
niconico data format changes causing all youtube-dl niconico folk broken

### ISSUE THREAD

**Issue by CXwudi** [tsukumijima/youtube-dl#3]
Hi tsukumijima,

Have you noticed this. A recent change of niconico has broken almost all niconico downloaders including yours. The change is basically just a data schema changes, not a big issue, you can refer to [this](https://github.com/AlexAplin/nndownload/issues/93) and [this ](https://github.com/animelover1984/youtube-dl/issues/29) issues for more details

I am looking for your fix soon

**Comment by tsukumijima** [comment]
Yes I know.
However, I haven't worked on youtube-dl recently. To be honest, I don't have the time and spare time to keep the youtube-dl fork up to date.
It is discussed at https://github.com/yt-dlp/yt-dlp/issues/171, and I think that the corresponding version will be released after a while. The niconico related code I wrote is also merged into yt-dlp. So I'm not going to implement it for now.

**Comment by CXwudi** [comment]
Thanks for letting me know and I am happy to hear that code you wrote is merged into one of the mainstream folk of youtube-dl. And thanks for providing this fix as it has helped me successfully download 200+ Vocaloid PV from niconico since 2020. Thanks :)

**Comment by tsukumijima** [comment]
Thank you too!
